### ISSUE TITLE
Repository is empty

### ISSUE THREAD

**Issue by rpherbig** [mhanberg/isBroken.js#1]
There is no code here, which makes it difficult for me to point out problems, point out non-problems, and open issues that can be closed without comment.

I suggest:
```
function isBroken(uselessArgWeArentGoingToUse) {
    http.requestFromMicroService(globalVariableWeAreGoingToMutate):

    globalVariableWeAreGoingToMutate.badlyNamedProperty
        ? throw new Error("Terrible error message")
        : throw new Error("Horrible error message");
}
```

**Comment by mhanberg** [comment]
this code is not compatible with the IE6, please add transpilation instructions.

**Comment by mhanberg** [comment]
Is this issue dead?
